id: AFC299A39
base_file: fBA84.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:30:00.236233
  last_modified_at: 2022-05-31 05:30:00.236241
