id: AFC299A39
base_file: fFEFD.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:30:00.239873
  last_modified_at: 2022-05-31 05:30:00.239879
